//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoicingApp.Web.Reports
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_InvoicePrint
    {
        public int Id { get; set; }
        public string InvoiceNumber { get; set; }
        public int ClientId { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public Nullable<System.DateTime> StratDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public int ChargeId { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<int> Units { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string CompanyName { get; set; }
        public string Contract { get; set; }
        public string ChargeSymbol { get; set; }
        public int CompanyId { get; set; }
    }
}
